CONVERT_TO = promicro_rp2040
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
AUTOCORRECT_ENABLE = yes
